
server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          # ADD Config Repository
          uri: https://github.com/Dokcer-DevLink/spring-configuration
          default-label: main
